version: "3"
services:
  web:
    container_name: webserver
    image: icg-app:latest
    ports:
    - 80:80
    - 443:443
    
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data
    env_file:
      - docker.env

  api:
    container_name: backendserver
    image: icg-app-rest:latest
    ports:
     - 2700:2700
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - docker.env
    command: node app/dist/main
