version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data
    env_file:
      - docker.env

  api:
    container_name: api-icg
    image: icg-app-rest:0.0.1-SNAPSHOT
    ports:
     - 2700:2700
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - docker.env
    command: node api/dist/main

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ${HOME}/data/pgadmin:/root/.pgadmin
  #   env_file:
  #     - docker.env
