# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Back end App

on:
  push:
    branches: [api/**, main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -f api/Dockerfile -t icg-app-rest
      - name: Stop Docker Image
        run: docker stop icg-app-rest || true && docker rm icg-app-rest || true
      - name: Run Docker Image
        run: docker run -d --name icg-app-rest -p 2700:2700 icg-app-rest
