# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment Rafele-pi

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: self-hosted

    if: github.event.pull_request.merged == true
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build the Docker image
        run: docker build -t icg-app .
      - name: Stop Docker Image
        run: docker stop icg-app || true && docker rm icg-app || true
      - name: Run Docker Image
        run: docker run -d --name icg-app -p 80:80 icg-app
