name: Deployment Front part

on:
  push:
    branches: [web/deploy, main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Build the Docker image
        run: docker build . -t icg-app -f web/Dockerfile
      - name: Stop Docker Image
        run: docker stop icg-app || true && docker rm icg-app || true
      - name: Run Docker Image
        run: docker run -d --name icg-app -p 80:80 icg-app
