name: Deployment Front part

on:
  push:
    branches: [web/deploy, main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.TOKEN_ARTIFACTS}}
          workflow: github-web.yml
          workflow_conclusion: success
          name: web-app
      - name: Print the final result
        shell: bash
        run: |
          value=`ls -l`
          echo The result is $value
      - name: Copy all file
        shell: bash
        run: |
          cp ./* /web/dist
      - name: Print /web/dist
        shell: bash
        run: |
          value=`ls -l /web/dist`
          echo The result is $value
      - name: Download Artifact
        run: gh run download -n web-app
      - name: Build the Docker image
        run: docker build . -t icg-app -f web/Dockerfile
      - name: Stop Docker Image
        run: docker stop icg-app || true && docker rm icg-app || true
      - name: Run Docker Image
        run: docker run -d --name icg-app -p 80:80 icg-app
