# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check GitHub Web

on:
  pull_request:
    branches: [web/**, main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "web"

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install Angular Cli
        run: npm install -g @angular/cli
      - name: install packages
        run: npm ci
      - name: Building application
        run: npm run build
      - name: Upload ftp icg-App
        uses: genietim/ftp-action@releases/v4
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "dist"
          remoteDir: "icg-app"
