# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check GitHub Web

on:
  pull_request:
    branches: [web/**, main]
  push:
    branches: [web/**, main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "web"

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install Angular Cli
        run: npm install -g @angular/cli
      - name: install packages
        run: npm ci
      - name: Building application
        run: npm run build
      - name: Remove node modules
        run: rm -rf node_modules
      - uses: actions/upload-artifact@v1
        with:
          name: nginx
          path: ./web/nginx.conf
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./web/dist/
  deploy:
    needs: build #this job depends on build job (run after when the build job completed)
    name: Deploy artifacts to ftp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: nginx
      - name: Upload nginx config file
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "icg-app/web/"
      - uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Upload ftp icg-App web
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "icg-app/web/dist/"
