name: Check building Web

on:
  push:
    branches: [web/**, web-deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "web"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: "npm"
      - name: install Angular Cli
        run: npm install -g @angular/cli
      - name: install packages
        run: npm ci
      - name: Building application
        run: npm run build
