name: Check GitHub Api

on:
  push:
    branches: [api/**, api-deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "api"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: "npm"
      - name: install packages
        run: npm install
      - name: Building application
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-app
          path: api/dist
          retention-days: 1
