name: Run Docker compose

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Running docker compose
        run: docker-compose up -d --force-recreate
