name: Run Docker compose

on:
  push:
    branches: [main]

jobs:
  docker-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Update resources
        run: echo ${{secrets.DEPLOY_VARIABLES}} > docker.env
      - name: List DEPLOY_VARIABLES
        run: cat docker.env
      - name: Running docker compose
        run: docker-compose up -d --force-recreate
