name: Run Docker compose

on:
  push:
    branches: [main]

jobs:
  docker-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Update resources
        uses: shine1594/secrets-to-env-action@master
        with:
          secrets: ${{ secrets.DEPLOY_VARIABLES }}
          secrets_env: all
          file_name_prod: docker.env
      - name: Running docker compose
        run: docker-compose up -d --force-recreate
