name: Run Docker compose

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Stopping docker compose
        run: docker-compose down
      - name: Running docker compose
        run: docker-compose up
