name: Run Docker compose

on:
  push:
    branches: [main]

jobs:
  docker-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: print secrets
        run: |
            echo $DEPLOY_VARIABLES | sed 's/ /\n/g' >> docker.env
            cat docker.env
        shell: bash
        env:
          DEPLOY_VARIABLES : ${{secrets.DEPLOY_VARIABLES}}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DEPLOY_VARIABLES
          path: docker.env
      - name: Running docker compose
        run: docker-compose up -d --force-recreate
